### ISSUE TITLE
Highlight matched part in picker (like live_grep)

### ISSUE THREAD

**Issue by Shatur** [nvim-telescope/telescope-live-grep-raw.nvim#1]
First of all thank you a lot for the awesome plugin!
I have a suggestion. With live_grep the matched part is highlighted:
![изображение](https://user-images.githubusercontent.com/22453358/140656493-e7aac35a-d5af-49f5-ae51-12dedd749f4d.png)
But this plugin doesn't do it:
![изображение](https://user-images.githubusercontent.com/22453358/140656506-3e022461-e674-44d5-8c45-da7a55330bf8.png)

Could we implement it?

**Comment by weeman1337** [comment]
We can use the `--json` option for `rg`.

[NeoVIM 0.6 is going to offer an API to `lua-cjson`](https://github.com/neovim/neovim/pull/14871). Means I would enable highlighting only if this API is available.

**Comment by Shatur** [comment]
> Means I would enable highlighting only if this API is available.

Just use `vim.fn.json_decode` until 0.6.

**Comment by Shatur** [comment]
> We can use the --json option for rg.

But I talking only about highlighting of matched part. It's already implemented in `live_grep`.

**Comment by weeman1337** [comment]
I think now I got it :) 

Can you give https://github.com/nvim-telescope/telescope-live-grep-raw.nvim/tree/feature-use-grep-sorter a try? It's using the default grep highlighter. Unfortunately it doesn't work if you run a more complex query. Utilising the JSON result for the sorter/previewer would be the best solution.

**Comment by Conni2461** [comment]
branch looks good. Thats only a workaround in telescope cores `live_grep` right now. Move to `json` is the way to go but was impossible with `vim.fn.json_*` because we are in a fast context and cant call `viml` at this point in time. `schedule` would be bad as well. So we need a `api-fast` function and `vim.json` is exactly that

**Comment by Shatur** [comment]
> Can you give https://github.com/nvim-telescope/telescope-live-grep-raw.nvim/tree/feature-use-grep-sorter a try?

Thanks, just what I need!

> Move to json is the way to go but was impossible with vim.fn.json_* because we are in a fast context and cant call viml at this point in time. schedule would be bad as well. So we need a api-fast function and vim.json is exactly that

Yeah... Hope 0.6 will be released soon.

**Comment by weeman1337** [comment]
Tested `feature-use-grep-sorter` for a couple of days. Works and merged to master.

I am going to create a new issue for the preview using `rg --json`

**Comment by ssh352** [comment]
for reference: fzf Rg has no such issue
